---
- name: Install Cowsay
  hosts: planetexpress:!farnsworth
  connection: ssh   # default is ssh
  gather_facts: true # runs by default
  
  tasks:

    - name: Install cosway app on ALL machines
      ansible.builtin.apt:
        name: cowsay
        state: present
      become: yes # run as sudo
