---
- name: Uninstall Cowsay
  hosts: planetexpress:!farnsworth
  connection: ssh   # default is ssh
  gather_facts: true # runs by default
  
  tasks:
    - name: Remove cosway app on ALL machines
      ansible.builtin.apt:
        name: cowsay
        state: absent
      become: yes # run as sudo